Dz12 l4
js-tasks-ru/htmlcss-20230124_svi-victoria pull request #14
Opened 2023-02-15 13:46 UTC by Victoria23022016

Добавляю решение ДЗ Аватар

2023-02-15 13:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-15 21:01 UTC, GSemikozov requested changes

2023-02-15 21:01 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 100%;
и height: 100%

2023-02-16 18:35 UTC, GSemikozov approved these changes

2023-02-16 18:35 UTC, merged