Dz04 l1
js-tasks-ru/htmlcss-20230124_svi-victoria pull request #5
Opened 2023-02-04 15:03 UTC by Victoria23022016

Добавлено решение задачи Аккордеон.

2023-02-04 15:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-07 09:44 UTC, GSemikozov requested changes

2023-02-07 09:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.card__accordion {
в файле стилей блока нельзя описывать сторонние блоки или какие-то вспомогательные стили, которые не относятся к блоку (обертки и прочее). Только класс блока + его элементы и модификаторы. И в принципе эта карточка в любом случае лишняя

2023-02-07 09:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding: 24px 48px 32px 32px;
снизу в закрытом состоянии 24

2023-02-07 09:44 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item[open] {
а в открытом - 32

2023-02-07 09:44 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <div class="card__accordion">
лишнее

2023-02-08 21:51 UTC, GSemikozov requested changes

2023-02-08 21:51 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 24px;
справа тоже нужен

2023-02-08 21:51 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +                <summary class="accordion__section">Accordion item 1</summary>
accordion__summary или accordion__heading

2023-02-09 13:48 UTC, GSemikozov requested changes

2023-02-09 13:48 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    padding-top: 24px;
все еще нет отступа справа)

2023-02-09 13:48 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item :last-child {
лишний пробел (синтаксическая ошибка)

2023-02-09 14:28 UTC, GSemikozov approved these changes

2023-02-09 14:28 UTC, merged