Dz06 l2
js-tasks-ru/htmlcss-20230124_svi-victoria pull request #6
Opened 2023-02-05 13:37 UTC by Victoria23022016

Добавлено решение ДЗ Гистограмма.

2023-02-05 13:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-06 10:56 UTC, GSemikozov requested changes

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +        <details class="accordion">
делаем не набор независимых аккордионов, а наоборот - 1 аккордион, у которого есть 3 секции. По структуре - нужно все 3 секции завернуть в общий div у которого будет класс блока .accordion, а секции - это соответственно элементы блока, например .accordion__item / .accordion__section

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
см. коммент ниже; это скорее элемент блока .accordion__item. На этом уровне можно задать отступ снизу + общие паддинги

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    display: inline-block;
лучше тогда block

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <p class="accordion__text">
контент может быть любым, не только параграф, поэтому - лучше использовать div

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
плюс - не отображено состояние .accordion__item[open] (паддинг снизу будет отличаться)

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__text {
скорее .accordion__content (а конкретно .accordion__text можно положить внутрь)

2023-02-06 10:56 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__text {
и - должен же быть отступ сверху?)

2023-02-06 11:02 UTC, GSemikozov requested changes

2023-02-06 13:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-02-06 13:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-06 15:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-02-10 14:55 UTC, GSemikozov requested changes

2023-02-10 14:55 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +        <div class="card">
блок - histogram, внутри - его элементы и модификаторы, card нам здесь не нужен)

2023-02-10 14:55 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="histogramm histogramm__title">
просто элемент histogramm__title, класс блока указывается лишь раз на самом верхнем уровне компонента

2023-02-10 14:55 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="histogramm histogramm__statistic">
тег `<p>`, просто histogramm__statistic

2023-02-10 14:55 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-align: end;
лишнее

2023-02-11 11:29 UTC, GSemikozov requested changes

2023-02-11 11:29 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <h1 class="histogramm__title">Total orders</h1>
`<p>`

2023-02-11 11:29 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <p class="histogramm__statistic">50254</p>
`<h4>`

2023-02-11 11:29 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <a class="histogramm__text"> View all </a>
histogramm__link)

2023-02-11 11:29 UTC, GSemikozov commented on assets/css/main.css
> -@import '../../components/card.css';
вопрос все еще актуален)

2023-02-11 11:29 UTC, GSemikozov commented on 04-lection2/01-histogram/card.css
> +.card {
и раз уж такая карточка не нужна - лучше ее сразу удалить)

2023-02-11 11:47 UTC, Victoria23022016 commented on assets/css/main.css
> -@import '../../components/card.css';
Я не помню, зачем я изначально этот файл подключала. Но поскольку в нем стили для card, которой больше нет в html файле, то зачем оставлять этот файл подключенным?

2023-02-14 18:18 UTC, GSemikozov approved these changes

2023-02-14 18:18 UTC, merged